services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qldt_db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc12345@@
      - MSSQL_PID=Express
    ports:
      - "11433:1433"
    volumes:
      - qldt_data:/var/opt/mssql
    networks:
      - app_network

  qldt-fe:
    build:
      context: ./QLDT_BECAMEX_FE
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - qldt-be
    networks:
      - app_network

  qldt-be:
    build:
      context: ./QLDT_BECAMEX_BE/QLDT_Becamex
      dockerfile: Dockerfile
    container_name: qldt_be
    restart: always
    ports:
      - "5228:5000"
    depends_on:
      - sqlserver
    networks:
      - app_network

volumes:
  qldt_data:

networks:
  app_network:
    driver: bridge
